language: python
python:
- '3.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: Woc7ghFas+eRlz4DQEcjSHoDlt1bNvBkKa7nh4xFmNJUzwfHBH8ZuBuSBV454s4vkuuJrAh/Gc3ey6g3zTf5s3mowfYFXDErBpxaXE4HTTI+qEEosHcFpVfR8+RgnnjUZMJPBChO1d8iksJM7QdC4+Uw+O0DJHKkIT32NfVRHKG1XP7fMZwZhonTM/x9+P5+rnFNW5uRzSistuMHBe82T6b3L4tZKXpQvXDFI2UlfLwp035/NieuWfqqXN06R9f8fzdfEnr45KlD4j58Df/51yozRqNMDN8H1/uo46HBODljiTfUGVDhdlh0R6DkyzHLdnTbFH079jY7GJE6wG9ab0AA7aFv4mU0GCbK6Vn34pGo12knwMi8wFysXkJvqrHhEqenw6AuMqAcuZv2Jbw6c1bxcpG13k0+lQmFHUbqIpcaisbuPzPaaZOPvDha19cZlQqrue+qLPhKDRhL7aMVQDUVMyX11AwlQd2TkOM1pTy4JwXkvHPZsfMXmq4TVEiWZ206fVzJ3u7MOMri9tmrG6gKSVDxCRl6CtfjPBAWF2p6VcvPovMTckwxUHQHhvfYXpCPSu3XmOH2Stt8YkwNKcuXYcENLocAw4+SBFFx5pLaxx+fDxbzOOdUHZtTOQ0Fd0cqnKUMtBNkXWyWMBGr0IwlhOm0nV0yMQ+Jvtw5hKs=
  app: kevs-taskr
  on:
    branch: master
    python: '3.6'
    repo: kev2718/flask-taskr
