language: python
python:
- '3.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: j77OutF2Yz1xZzDsXORjp2PyXE7E8hB8gIWoD99OR1WhwaQewoM5m/+PtvUCNpUsF1GKmcQipQKVPp1C8idDWnhF/toMgycdh3prEJc7ZotuuoyFV/aqGHtzTeppvb39HoFA8dPTotHCUEmpp83GxYQHYOFrxC3p5Qw529E/ZajnzDenja8eSIL1CTDK8FM5dHO9ZvtK54zco0+9KcafeOaETsd/zeDYsWWg2IqmxgHzPQfaNqwl3jI4+Ho9cVzes2QTn4DAHST1KBPBGQfwGHRrQybWmQr9RzNlTPtnxZ6Kh6botneZ5LkFGY+EU2QSyIB2pyjBGli1JJXRAe7jC3BwIs2XHvtGmA7M5sFLqnpVNRQK5Q5OytAFPDjwr1LSkVeqN+pjF1iU1Q+DDJyQD/uew1lC8gRA8YbWDpM+5Kq75OPBBt1NmgloliA90NF9j6nEJEBah1lf4fOUT9S3hGtBfjkPeZx/uRez85yrNkfJ7gQtdQn492yQzH5yNtrDaeGwFQFGao+WMvdcnvQYnXfv9FaxdVSWTAlzoZ8jRi+aAFT1TR2arYq6tkBBsxUxrRuoudx6VhTAJCh6IjqZPFAFTX5US/993Oq0qC7BaaMVh0k2C2BjN32G9ojSA+JQMcROpRumKpX/CKcN8FHWhjoweHOKgxM2KNkQVB7hWHY=
  app: flask-taskr
  on:
    repo: kev2718/flask-taskr
